name: CI pipeline 

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
   
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: 
          python pip install --upgrade pip
          python pip install -r requirements.txt

      - name: Run tests
        run: 
          python pytest

      - name: build docker image
        run: 
          docker build -t github-actions-demo:${{ github.sha }} .
    